import {menus,shiftDay,calendar,latestDocuments,monthlySnapshot,documentBody,exportDocument} from './portal.mjs?v=20261007-single-sheet';
import {escapeHTML as e,monday,monthReports,summarize,csv,validateItems,canEditReport} from './core.mjs';
import {weeklySnapshot,weeklyBody,weeklyFile} from './weekly.mjs?v=20261007-taskids';
const $=s=>document.querySelector(s), root=$('#app');
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const cfg=window.REPORT_CONFIG||{}, configured=!!(cfg.supabaseUrl&&cfg.publishableKey);
let client,user,me,members=[],reports=[],view='dashboard',month=today.slice(0,7),week=monday(today),editing=null,demo=false,busy=false;
const fields=['콘텐츠 운영','플랫폼 운영','콘텐츠 신규','플랫폼 신규','AX/업무 효율화','AX/신규'],services=['팜빌','닥터빌','배터빌'];
const itemId=(r,i,n)=>i.id||('TASK-'+r.id+'-'+String(n+1).padStart(2,'0'));
const blankItem=()=>({id:'TASK-'+crypto.randomUUID(),project:'',service:'',target_date:'',title:'',state:'진행',progress:0,result:''});
let formItems=[blankItem()],documents=[],calendarMonth=today.slice(0,7),selectedDocument=null,storageError='';
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500)}
async function run(fn){if(busy)return;busy=true;const blocked=[...document.querySelectorAll('button')].map(b=>[b,b.disabled]);blocked.forEach(([b])=>b.disabled=true);try{await fn()}catch(err){toast(err.message||'처리하지 못했습니다. 다시 시도해주세요.')}finally{busy=false;blocked.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled})}}
function name(id){return members.find(m=>m.id===id)?.name||'알 수 없는 팀원'}
const badge=s=>`<span class="pill ${s==='완료'?'done':s==='보류'?'hold':''}">${e(s)}</span>`;
function shell(content){root.innerHTML=`<header><div class="brand">팀워크<small>WEEKLY REPORT</small></div><div class="actions"><span class="small">${e(me.name)} · ${e(me.team)}${me.role==='admin'?' · 관리자/책임자':''}</span><button id="logout">${demo?'데모 나가기':'로그아웃'}</button></div></header>${demo?'<div class="banner">데모 모드 · 가상 데이터로 체험 중입니다. 변경 사항은 이 브라우저에만 저장되며 팀원과 공유되지 않습니다.</div>':''}<div class="shell"><aside><nav>${menus.filter(([v])=>v!=='members'||me.role==='admin').map(([v,t])=>`<button data-view="${v}" class="${view===v?'active':''}">${t}</button>`).join('')}</nav><div class="aside-note">주간 기록이<br>월간 성과가 됩니다.<br><br>제출된 보고는 팀원 모두에게 공유됩니다. 임시저장은 본인에게만 보입니다.</div></aside><main>${content}</main></div>`;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;editing=null;formItems=[blankItem()];if(view==='write'){week=monday(today);editing=reports.find(r=>r.user_id===user.id&&r.week_start===week)||null;if(editing)formItems=editing.items.map((i,n)=>({...structuredClone(i),id:itemId(editing,i,n)}));}render()});$('#logout').onclick=()=>run(async()=>{if(!demo)await client.auth.signOut();demo=false;user=null;login()});}
function monthControl(){return `<div><label for="month">기준 월</label><input id="month" type="month" value="${month}"></div>`}
function reportCard(r){return `<article class="report-card"><div class="report-title"><div><strong>${e(name(r.user_id))}</strong> <span class="muted">${e(r.week_start)} 주간</span></div><div>${badge(r.status==='submitted'?'제출':'임시저장')} ${canEditReport(me,r)?`<button data-edit="${e(r.id)}" class="small no-print">수정</button>`:''}</div></div><details><summary>업무 ${r.items.length}건 보기</summary>${r.items.map(i=>`<div class="item"><h3>${e(i.project)} · ${e(i.title)}</h3>${badge(i.state)} <span class="muted">진행률 ${i.progress}% · 서비스 ${e(i.service||'미지정')} · 목표 일정 ${e(i.target_date||'미지정')}</span><p class="detail">${e(i.result||'성과 미입력')}</p></div>`).join('')}<p class="detail"><strong>이슈 및 지원 요청</strong><br>${e(r.issues||'없음')}</p><p class="detail"><strong>다음 주 계획</strong><br>${e(r.next_plan||'없음')}</p></details></article>`}
function bindCards(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=reports.find(r=>r.id===b.dataset.edit);week=editing.week_start;formItems=editing.items.map((i,n)=>({...structuredClone(i),id:itemId(editing,i,n)}));view='edit';render()})}
function dashboard(){const w=monday(today),deadline=shiftDay(w,4),rs=reports.filter(r=>r.week_start===w&&r.status==='submitted');shell('<div class="topline"><div><h1>홈</h1><p>이번 주 '+w+' ~ '+shiftDay(w,6)+' · 제출 마감: '+deadline+' 금요일</p><p class="muted">'+(today>deadline?'금요일 마감이 지났습니다. 미제출 보고를 확인해주세요.':'매주 금요일까지 주간 보고를 완료해주세요.')+'</p></div><button id="home-refresh">현황 새로고침</button></div><div class="stats"><div class="stat"><span>제출 완료</span><strong>'+rs.length+' / '+members.length+'</strong></div><div class="stat"><span>미제출</span><strong>'+(members.length-rs.length)+'</strong></div></div><section class="panel"><h2>팀원별 금주 제출 현황</h2>'+members.map(m=>{const r=rs.find(r=>r.user_id===m.id);return '<div class="member"><span>'+e(m.name)+' · '+e(m.team)+'</span><span>'+badge(r?'제출 완료':today>deadline?'마감 지연':'미제출')+(r?' · '+e(new Date(r.updated_at||today+'T00:00:00Z').toLocaleString('ko-KR')):'')+'</span></div>'}).join('')+'</section><section class="panel"><h2>금주 제출 보고</h2>'+(rs.map(reportCard).join('')||'<p>아직 제출된 보고가 없습니다.</p>')+'</section>');$('#home-refresh').onclick=()=>run(async()=>{if(!demo)await load();render()});bindCards()}
function choices(values,current){return '<option value="">선택해주세요</option>'+(!values.includes(current)&&current?'<option value="'+e(current)+'" selected>'+e(current)+' (기존 값)</option>':'')+values.map(v=>'<option value="'+e(v)+'" '+(v===current?'selected':'')+'>'+e(v)+'</option>').join('')}
function itemFields(i,n){return '<div class="item" data-item="'+n+'"><div class="item-head"><h3>업무 '+String(n+1).padStart(2,'0')+'</h3><span class="muted">ID: '+e(i.id||'저장 시 부여')+'</span><button type="button" data-remove="'+n+'" class="small">삭제</button></div><div class="grid"><div class="field"><label>업무 분야<select data-field="project" required>'+choices(fields,i.project)+'</select></label></div><div class="field"><label>서비스<select data-field="service" required>'+choices(services,i.service||'')+'</select></label></div><div class="field"><label>업무 내용<input data-field="title" maxlength="300" value="'+e(i.title)+'" required></label></div><div class="field"><label>상태<select data-field="state">'+['진행','완료','보류'].map(v=>'<option '+(v===i.state?'selected':'')+'>'+v+'</option>').join('')+'</select></label></div><div class="field"><label>목표 일정<input data-field="target_date" type="date" value="'+e(i.target_date||'')+'"></label></div><div class="field"><label>진행률 (%)<select data-field="progress" required>'+Array.from({length:21},(_,n)=>n*5).map(v=>'<option value="'+v+'" '+(v===i.progress?'selected':'')+'>'+v+'%</option>').join('')+'</select></label></div></div><label>주요 성과 · 수치 · 결과<textarea data-field="result" maxlength="3000">'+e(i.result)+'</textarea></label></div>'}
function capture(){const previous=formItems;formItems=[...document.querySelectorAll('[data-item]')].map(el=>({...previous[Number(el.dataset.item)],...Object.fromEntries([...el.querySelectorAll('[data-field]')].map(f=>[f.dataset.field,f.dataset.field==='progress'?Number(f.value):f.value]))}))}
function write(){const owner=editing?members.find(m=>m.id===editing.user_id):me;const other=editing&&editing.user_id!==user.id;shell(`<div class="topline"><div><h1>${view==='edit'?'주간 업무 보고 수정':'금주 주간 업무 작성'}</h1><div class="muted">핵심 업무와 성과를 간단히 기록하세요.</div></div>${badge(editing?.status==='submitted'?'제출 보고 수정':'작성 중')}</div><form id="report-form"><section class="panel"><div class="grid"><div><label for="week">보고 주간 (월요일 기준)</label><input id="week" type="date" value="${week}" required></div><div><label>작성자</label><input value="${e(owner.name+' · '+owner.team)}" disabled></div></div><p class="muted">월 성과보고는 주간 시작일이 속한 월에 포함됩니다.</p>${taskPicker(owner.id)}<div id="items">${formItems.map(itemFields).join('')}</div><button id="add" type="button">업무 추가</button></section><section class="panel"><div class="field"><label for="issues">이슈 및 지원 요청</label><textarea id="issues" maxlength="5000" placeholder="진행을 막는 문제나 필요한 지원">${e(editing?.issues||'')}</textarea></div><label for="next-plan">다음 주 계획</label><textarea id="next-plan" maxlength="5000" placeholder="다음 주에 집중할 업무">${e(editing?.next_plan||'')}</textarea></section><div class="actions right">${other?'':'<button id="draft" type="button">임시저장</button>'}<button class="primary" type="submit">${editing?.status==='submitted'?'수정 후 제출':'보고 제출'}</button></div></form>`);
const rebind=()=>{document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{capture();formItems.splice(Number(b.dataset.remove),1);$('#items').innerHTML=formItems.map(itemFields).join('');rebind()});document.querySelectorAll('[data-field="state"]').forEach(s=>s.onchange=()=>{if(s.value==='완료')s.closest('[data-item]').querySelector('[data-field="progress"]').value=100})};rebind();bindTaskPicker(owner.id,rebind);$('#add').onclick=()=>{capture();formItems.push(blankItem());$('#items').innerHTML=formItems.map(itemFields).join('');rebind()};$('#week').onchange=ev=>{if(!ev.target.value)return;week=monday(ev.target.value);ev.target.value=week};$('#week').disabled=true;if($('#draft'))$('#draft').onclick=()=>run(()=>save('draft'));$('#report-form').onsubmit=ev=>{ev.preventDefault();run(()=>save('submitted'))}}
async function save(status){const ownerId=editing?.user_id||user.id;if(editing&&!canEditReport(me,editing))throw Error('수정 권한이 없습니다.');if(ownerId!==user.id&&status!=='submitted')throw Error('관리자는 제출 상태를 유지해야 합니다.');capture();validateItems(formItems);if(formItems.some(i=>!services.includes(i.service)||i.progress%5!==0))throw Error('서비스와 5% 단위 진행률을 선택해주세요.');if(!$('#week').value)throw Error('보고 주간을 선택해주세요.');const start=monday($('#week').value),existing=reports.find(r=>r.user_id===ownerId&&r.week_start===start);if(existing&&existing.id!==editing?.id)throw Error('해당 주간의 보고가 이미 있습니다. 팀 보고 현황에서 기존 보고를 수정해주세요.');const r={user_id:ownerId,week_start:start,status,items:formItems,issues:$('#issues').value.trim(),next_plan:$('#next-plan').value.trim(),updated_at:new Date().toISOString()};if(demo){r.id=editing?.id||crypto.randomUUID();reports=reports.filter(x=>x.id!==r.id).concat(r);localStorage.setItem('teamwork-demo-reports',JSON.stringify(reports))}else{const q=editing?client.from('reports').update(r).eq('id',editing.id).eq('updated_at',editing.updated_at).select():client.from('reports').insert(r).select();const {data,error}=await q;if(error)throw error;if(!data?.length)throw Error('저장하지 못했습니다. 다른 창에서 변경됐을 수 있습니다. 새로고침 후 최신 보고로 다시 수정해주세요.');await load()}view='edit';week=start;calendarMonth=start.slice(0,7);month=start.slice(0,7);editing=null;formItems=[blankItem()];render();toast(status==='draft'?'임시저장했습니다.':'보고를 제출했습니다.')}
function monthly(){const rs=reports.filter(r=>r.status==='submitted'&&r.week_start.startsWith(month)),saved=documents.filter(d=>d.kind==='monthly');shell('<h1>월 성과 보고서 생성</h1><section class="panel"><div class="toolbar">'+monthControl()+'<button id="generate-monthly" class="primary" '+(!rs.length||storageError?'disabled':'')+'>월 성과 요약보고서 생성</button></div><p>제출 보고 '+rs.length+'건 · 동일 업무 ID는 월 내 최신 상태로 요약하고 주별 성과를 종합합니다.</p>'+storageNotice()+'</section><section class="panel"><h2>생성 완료 목록</h2>'+(saved.map(d=>'<article class="report-card"><strong>'+e(d.period)+' 월 성과보고</strong><p>'+e(new Date(d.created_at).toLocaleString('ko-KR'))+' · '+e(d.snapshot.author)+'</p>'+documentActions(d)+'</article>').join('')||'<p>생성된 보고서가 없습니다.</p>')+'</section><section id="document-preview" class="panel">'+(selectedDocument?.kind==='monthly'?documentBody(selectedDocument.snapshot,'monthly'):'목록에서 보고서 보기를 선택해주세요.')+'</section>');$('#month').onchange=ev=>{month=ev.target.value||month;selectedDocument=null;render()};$('#generate-monthly').onclick=()=>run(async()=>{if(!demo)await load();await persistDocument(monthlySnapshot(reports,members,month,me.name),'monthly',month);render();toast(demo?'데모 월 성과보고서를 생성했습니다.':'월 성과보고서를 생성하고 공용 저장소에 보관했습니다.')});bindDocumentActions()}
function render(){if(!me)return;({dashboard,write,edit:editPage,monthly,weekly:weeklyPage,files:filePage,members:memberPage}[view])()}
const archiveKey=()=>`teamwork-weekly-files:${cfg.supabaseUrl||'demo'}:${demo?'demo':user.id}`;
function archives(){try{return JSON.parse(localStorage.getItem(archiveKey())||'[]')}catch{return []}}
function downloadWeekly(s){const url=URL.createObjectURL(new Blob([weeklyFile(s)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`주간_통합보고_${s.week}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function weeklyPage(){const rs=reports.filter(r=>r.status==='submitted'&&r.week_start===week);shell('<h1>주간 업무 보고 통합 문서 생성</h1><section class="panel"><div class="toolbar"><label>보고 주간<input id="aggregate-week" type="date" value="'+week+'"></label><button id="aggregate-refresh">최신 보고 조회</button><button id="generate-weekly" class="primary" '+(!rs.length||storageError?'disabled':'')+'>통합 문서 생성 / 최신 버전 저장</button><button id="weekly-pdf" '+(!rs.length||storageError?'disabled':'')+'>PDF 다운로드</button><button id="weekly-excel" '+(!rs.length||storageError?'disabled':'')+'>Excel 다운로드 (.xlsx)</button><button id="weekly-html" '+(!rs.length||storageError?'disabled':'')+'>HTML 다운로드</button></div><p>제출 '+rs.length+' / '+members.length+'명. 생성된 마지막 버전은 관리자와 팀원이 저장소에서 함께 열람합니다.</p><p class="muted">현재 기본 양식을 사용합니다. 업로드하실 양식은 추후 반영합니다. 이슈와 계획은 [카테고리] 또는 카테고리: 내용 형식으로 묶습니다.</p>'+storageNotice()+'</section><section class="panel">'+(rs.length?weeklyBody({week,created_at:new Date().toISOString(),author:me.name,members,reports:rs}):'제출된 보고가 없습니다.')+'</section>');$('#aggregate-week').onchange=ev=>{if(ev.target.value){week=monday(ev.target.value);render()}};$('#aggregate-refresh').onclick=()=>run(async()=>{if(!demo)await load();render()});$('#generate-weekly').onclick=()=>run(async()=>{if(!demo)await load();await persistDocument(weeklySnapshot(reports,members,week,me.name),'weekly',week);calendarMonth=week.slice(0,7);view='files';render();toast('통합 문서의 최신 버전을 저장했습니다.')});const output=format=>run(async()=>{if(!demo)await load();await persistDocument(weeklySnapshot(reports,members,week,me.name),'weekly',week);const generated=selectedDocument;render();await exportDocument(generated.snapshot,'weekly',format)});$('#weekly-pdf').onclick=()=>output('pdf');$('#weekly-excel').onclick=()=>output('xlsx');$('#weekly-html').onclick=()=>output('html')}
function filePage(){const saved=latestDocuments(documents.filter(d=>d.kind==='weekly')),d=saved.find(d=>d.period===week);shell('<h1>주간 업무 보고서 저장소</h1>'+storageNotice()+calendar(calendarMonth,week,new Set(saved.map(d=>d.period)))+'<section class="panel"><h2>'+e(week)+' 주간 · 마지막 생성 버전</h2>'+(d?'<p>생성 '+e(new Date(d.created_at).toLocaleString('ko-KR'))+' · '+e(d.snapshot.author)+'</p>'+documentActions(d)+documentBody(d.snapshot):'<p>해당 주의 통합 문서가 없습니다. 통합 문서 생성 메뉴에서 생성해주세요.</p>')+'</section>');bindCalendar(()=>render());bindDocumentActions()}
async function load(){const [m,r]=await Promise.all([client.from('members').select('*').order('name'),client.from('reports').select('*').order('week_start',{ascending:false})]);if(m.error)throw m.error;if(r.error)throw r.error;members=m.data;reports=r.data;me=members.find(m=>m.id===user.id);if(!me)throw Error('등록된 팀원이 아닙니다. 관리자에게 팀원 등록을 요청해주세요.');const d=await client.from('report_documents').select('*').order('created_at',{ascending:false});storageError=d.error?'공용 보고서 저장소 설정이 필요합니다. 관리자에게 문의해주세요.':'';documents=d.data||[];}
function startDemo(){demo=true;storageError='';documents=JSON.parse(localStorage.getItem('teamwork-demo-documents')||'[]');user={id:'demo-me'};members=[{id:'demo-me',name:'김민수',team:'사업전략팀',role:'admin'},{id:'demo-2',name:'이지연',team:'사업전략팀'},{id:'demo-3',name:'박준호',team:'개발팀'}];me=members[0];const sample=members.map((m,n)=>({id:'sample-'+n,user_id:m.id,week_start:monday(today),status:'submitted',items:[{project:['파트너 제휴','서비스 운영','제품 개발'][n],title:['신규 제휴사 상담 및 계약','고객 문의 프로세스 개선','주간 보고 화면 개발'][n],state:n===2?'진행':'완료',progress:n===2?70:100,result:['제휴 후보 8개사 상담, 3개사 계약 완료','반복 문의 12건 분석 및 안내 문서 개선','입력 화면 구현 완료, 월 취합 기능 검토 중'][n]}],issues:n===2?'테스트 일정 조율 필요':'',next_plan:['후속 제휴사 미팅 진행','안내 문서 팀 공유','월 취합 기능 테스트'][n]}));try{reports=JSON.parse(localStorage.getItem('teamwork-demo-reports')||'null')||sample}catch{reports=sample}view='dashboard';render()}
function login(message=''){root.innerHTML=`<header><div class="brand">팀워크<small>WEEKLY REPORT</small></div></header><main><section class="panel auth"><span class="pill">팀 주간 업무 보고</span><h1 style="margin-top:18px">이번 주의 업무를<br>한곳에 모으세요.</h1><p class="muted">주간 업무 기록부터 월 성과보고까지.<br>등록된 팀원만 로그인할 수 있습니다.</p>${!configured?'<div class="banner warning">공용 저장소 연결 전입니다. 아래 데모로 작성과 취합 기능을 체험하세요.</div>':`<form id="login-form"><div class="field"><label for="email">업무 이메일</label><input id="email" type="email" autocomplete="username" required></div><div class="field"><label for="password">비밀번호</label><input id="password" type="password" autocomplete="current-password" required></div><button class="primary" type="submit">로그인</button><button id="reset" type="button">비밀번호 설정 / 재설정</button></form>`}<p class="error" id="auth-error">${e(message)}</p><button id="demo">데모 체험</button><p class="muted">데모에는 가상의 팀원과 업무만 표시됩니다.</p></section></main>`;$('#demo').onclick=startDemo;if(configured){$('#login-form').onsubmit=ev=>{ev.preventDefault();run(async()=>{const {data,error}=await client.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)throw Error('이메일 또는 비밀번호를 확인해주세요.');user=data.user;try{await load();view='dashboard';render()}catch(err){await client.auth.signOut();user=null;login(err.message)}})};$('#reset').onclick=()=>run(async()=>{const email=$('#email').value.trim();if(!email||!$('#email').checkValidity())throw Error('이메일을 입력해주세요.');const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;toast('등록된 이메일이라면 비밀번호 설정 메일이 발송됩니다.')})}}
function passwordScreen(){root.innerHTML='<main><form id="password-form" class="panel auth"><h1>비밀번호 설정</h1><p class="muted">팀 보고에 사용할 비밀번호를 설정하세요.</p><label for="new-password">새 비밀번호 (12자 이상)</label><input id="new-password" type="password" minlength="12" autocomplete="new-password" required><p><button class="primary">저장 후 로그인</button></p></form></main>';$('#password-form').onsubmit=ev=>{ev.preventDefault();run(async()=>{const {error}=await client.auth.updateUser({password:$('#new-password').value});if(error)throw error;await client.auth.signOut();history.replaceState(null,'',location.pathname);login();toast('비밀번호를 설정했습니다. 로그인해주세요.')})}}
async function init(){if(!configured){login();return}root.innerHTML='<main><div class="panel">로그인 정보를 확인하고 있습니다…</div></main>';try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');client=createClient(cfg.supabaseUrl,cfg.publishableKey);let recovery=false;client.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){recovery=true;passwordScreen()}});const {data,error}=await client.auth.getSession();if(error)throw error;if(recovery||/type=(recovery|invite)/.test(location.hash)){passwordScreen();return}user=data.session?.user;if(user){await load();render()}else login()}catch(err){login('연결을 확인해주세요: '+err.message)}}
init();

function memberPage(){if(me.role!=='admin'){view='dashboard';dashboard();return}shell('<h1>팀원 관리</h1><section class="panel"><h2>계정 추가 등록</h2><p>Supabase Authentication에 생성된 로그인 계정을 이메일로 찾아 팀원에 등록합니다. 신규 로그인 계정 생성은 아래 관리 화면에서 진행합니다.</p><a href="https://supabase.com/dashboard/project/qoabsfqxufdzcjhgrceq/auth/users" target="_blank" rel="noopener">로그인 계정 생성 화면 열기</a><form id="register-member"><div class="grid"><label>계정 이메일<input name="email" type="email" required></label><label>표시 이름<input name="name" maxlength="100" required></label><label>소속<input name="team" maxlength="100" required></label></div><button class="primary">일반 팀원으로 등록</button></form></section>'+members.map(m=>'<form class="panel member-form" data-member="'+e(m.id)+'"><div class="grid"><label>표시 이름<input name="name" value="'+e(m.name)+'" maxlength="100" required></label><label>소속<input name="team" value="'+e(m.team)+'" maxlength="100" required></label></div><p>'+e(m.role==='admin'?'관리자/책임자':'일반 팀원')+' · ID: '+e(m.id)+'</p><button class="primary">정보 저장</button></form>').join(''));$('#register-member').onsubmit=ev=>{ev.preventDefault();run(async()=>{if(demo)throw Error('데모에서는 실제 계정을 등록하지 않습니다.');const v=new FormData(ev.target);const {error}=await client.rpc('register_team_member',{account_email:v.get('email').trim(),display_name:v.get('name').trim(),team_name:v.get('team').trim()});if(error)throw error;await load();render();toast('일반 팀원 계정을 등록했습니다.')})};document.querySelectorAll('.member-form').forEach(f=>f.onsubmit=ev=>{ev.preventDefault();run(async()=>{const v=new FormData(f),name=v.get('name').trim(),team=v.get('team').trim();if(!name||!team)throw Error('이름과 소속을 입력해주세요.');if(demo){Object.assign(members.find(m=>m.id===f.dataset.member),{name,team})}else{const {data,error}=await client.from('members').update({name,team}).eq('id',f.dataset.member).select();if(error)throw error;if(!data.length)throw Error('저장 권한을 확인해주세요.');await load()}render();toast('팀원 정보를 저장했습니다.')})})}
function taskCatalog(ownerId){const catalog=new Map();for(const r of reports.filter(r=>r.user_id===ownerId).slice().sort((a,b)=>b.week_start.localeCompare(a.week_start)))r.items.forEach((i,n)=>{const id=itemId(r,i,n);if(!catalog.has(id))catalog.set(id,{...i,id,sourceWeek:r.week_start})});return [...catalog.values()]}
function taskPicker(ownerId){return '<section class="panel"><h2>기존 업무 불러오기</h2><p class="muted">업무 ID 또는 업무내용으로 검색해 불러오세요. 같은 ID로 다음 주 진행상황을 기록할 수 있습니다. 과거 보고는 변경되지 않습니다.</p><label>기존 업무 검색<input id="task-search" type="search" placeholder="업무 ID, 분야, 서비스, 업무내용"></label><label>기존 업무 선택<select id="task-select"></select></label><button id="load-task" type="button">선택 업무 불러오기</button></section>'}
function bindTaskPicker(ownerId,rebind){const catalog=taskCatalog(ownerId);const refresh=()=>{const q=$('#task-search').value.toLowerCase().trim();$('#task-select').innerHTML='<option value="">기존 업무를 선택해주세요</option>'+catalog.filter(i=>[i.id,i.title,i.project,i.service].join(' ').toLowerCase().includes(q)).map(i=>'<option value="'+e(i.id)+'">'+e(i.sourceWeek+' · '+i.title+' · '+i.id)+'</option>').join('')};refresh();$('#task-search').oninput=refresh;$('#load-task').onclick=()=>{const item=catalog.find(i=>i.id===$('#task-select').value);if(!item){toast('불러올 업무를 선택해주세요.');return}capture();if(formItems.some(i=>i.id===item.id)){toast('이미 작성 중인 업무입니다. 아래에서 수정해주세요.');return}formItems=formItems.filter(i=>i.project||i.title||i.result||i.service||i.target_date);const {sourceWeek,...values}=item;formItems.push(structuredClone(values));$('#items').innerHTML=formItems.map(itemFields).join('');rebind();toast('기존 업무를 불러왔습니다. 변경된 내용만 수정해주세요.')};}

function storageNotice(){return storageError?'<div class="banner warning">'+e(storageError)+'</div>':demo?'<p class="muted">데모 보고서는 현재 브라우저에만 저장됩니다.</p>':'<p class="muted">공용 저장소 · 등록된 관리자와 팀원이 함께 열람합니다.</p>'}
function bindCalendar(callback){$('#cal-month').onchange=ev=>{if(ev.target.value){calendarMonth=ev.target.value;callback()}};const move=n=>{calendarMonth=shiftDay(calendarMonth+'-15',n*31).slice(0,7);callback()};$('#cal-prev').onclick=()=>move(-1);$('#cal-next').onclick=()=>move(1);document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{week=monday(b.dataset.day);editing=null;callback()})}
function editPage(){const own=reports.filter(r=>r.user_id===user.id);shell('<h1>주간 업무 보고 수정</h1><p>본인이 작성한 주간 보고의 최종 버전만 조회·수정할 수 있습니다.</p>'+calendar(calendarMonth,week,new Set(own.map(r=>r.week_start)))+'<section id="edit-content"></section>');bindCalendar(()=>render());const r=own.find(r=>r.week_start===week);if(!r){$('#edit-content').innerHTML='<section class="panel">선택한 주에 본인이 작성한 보고가 없습니다.</section>';return}editing=r;formItems=r.items.map((i,n)=>({...structuredClone(i),id:itemId(r,i,n)}));const calendarHTML=document.querySelector('.calendar').outerHTML;write();$('main').insertAdjacentHTML('afterbegin',calendarHTML);bindCalendar(()=>render());}
function documentActions(d){return '<div class="actions no-print"><button data-doc-view="'+e(d.id)+'">보고서 보기</button>'+['docx','pdf',...(d.kind==='weekly'?['xlsx']:[]),'html'].map(f=>'<button data-doc="'+e(d.id)+'" data-format="'+f+'">'+({docx:'Word',pdf:'PDF',xlsx:'Excel',html:'HTML'}[f])+' 다운로드</button>').join('')+'</div>'}
function bindDocumentActions(){document.querySelectorAll('[data-doc-view]').forEach(b=>b.onclick=()=>{const d=documents.find(d=>d.id===b.dataset.docView);if(!d)return;selectedDocument=d;if(view==='monthly'){render();$('#document-preview').scrollIntoView({behavior:'smooth'})}else document.querySelector('.calendar').nextElementSibling.scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>run(async()=>{const d=documents.find(d=>d.id===b.dataset.doc);if(d)await exportDocument(d.snapshot,d.kind,b.dataset.format)}))}
async function persistDocument(snapshot,kind,period){if(storageError)throw Error(storageError);const d={id:snapshot.id,kind,period,snapshot,created_by:user.id,created_at:snapshot.created_at};if(demo){documents.unshift(d);localStorage.setItem('teamwork-demo-documents',JSON.stringify(documents))}else{const {data,error}=await client.rpc('generate_report_document',{document_kind:kind,document_period:period});if(error)throw error;Object.assign(d,Array.isArray(data)?data[0]:data);await load()}selectedDocument=d;}
