import {groupedNotes} from './weekly.mjs';
export function weeklyExcelRows(s){const person=id=>s.members.find(m=>m.id===id)?.name||'미등록';return {
 tasks:[['프로젝트','업무내용','상태','목표 일정','진행률','업무담당자','주요성과','서비스','업무 ID'],...s.reports.flatMap(r=>r.items.map(i=>[i.project,i.title,i.state,i.target_date?new Date(i.target_date+'T00:00:00Z'):null,i.progress/100,person(r.user_id),i.result||'',i.service||'',i.id||''])).sort((a,b)=>a[0].localeCompare(b[0],'ko'))],
 issues:[['카테고리','이슈 및 지원 요청','담당자'],...groupedNotes(s.reports,'issues').flatMap(g=>g.entries.map(x=>[g.category,x.text,x.owners.map(person).join(', ')]))],
 plans:[['카테고리','다음 주 계획','담당자'],...groupedNotes(s.reports,'next_plan').flatMap(g=>g.entries.map(x=>[g.category,x.text,x.owners.map(person).join(', ')]))]
}}
let excelModule;
export async function weeklyExcelBlob(s){excelModule ||= new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';script.onload=()=>resolve(window.ExcelJS);script.onerror=()=>{excelModule=null;reject(Error('Excel 모듈을 불러오지 못했습니다. 네트워크를 확인해주세요.'))};document.head.append(script)});const ExcelJS=await excelModule,book=new ExcelJS.Workbook(),data=weeklyExcelRows(s);book.creator=s.author;book.created=new Date(s.created_at);
 for(const [key,title,widths] of [['tasks','주간 통합 업무',[22,48,12,15,12,18,58,14,42]],['issues','이슈 및 지원 요청',[22,75,28]],['plans','다음 주 계획',[22,75,28]]]){const sheet=book.addWorksheet(title,{views:[{state:'frozen',ySplit:4}],pageSetup:{paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,printTitlesRow:'1:4'}});sheet.columns=widths.map(width=>({width}));sheet.mergeCells(1,1,1,widths.length);sheet.getCell(1,1).value=s.week+' 주간 통합보고 · '+title;sheet.getCell(1,1).font={name:'맑은 고딕',size:16,bold:true,color:{argb:'FF17365D'}};sheet.getRow(1).height=30;sheet.mergeCells(2,1,2,widths.length);sheet.getCell(2,1).value='생성: '+new Date(s.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' · 작성: '+s.author+' · 제출 '+s.reports.length+'건';sheet.getRow(2).height=24;data[key].forEach((values,n)=>{const row=sheet.getRow(n+4);row.values=values;row.height=n?Math.min(220,Math.max(38,...values.map((v,c)=>Math.ceil(String(v??'').length/(widths[c]*0.7))*16))):28;row.eachCell({includeEmpty:true},cell=>{cell.font={name:'맑은 고딕',size:11,...(!n?{bold:true,color:{argb:'FFFFFFFF'}}:{})};cell.alignment={vertical:'top',wrapText:true};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:!n?'FF17365D':n%2?'FFF0F5FC':'FFFFFFFF'}};cell.border={bottom:{style:'thin',color:{argb:'FFD9E2F0'}}}});if(key==='tasks'&&n){row.getCell(4).numFmt='yyyy-mm-dd';row.getCell(5).numFmt='0%'}});if(data[key].length===1){sheet.getCell(5,2).value='없음';sheet.getRow(5).height=30}sheet.autoFilter={from:{row:4,column:1},to:{row:4,column:widths.length}};sheet.pageSetup.printArea='A1:'+String.fromCharCode(64+widths.length)+(Math.max(5,data[key].length+3));}
 return new Blob([await book.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
