import {escapeHTML as e} from './core.mjs';
export const metricTitles=['1. 주요 지표 · 회원 및 활동성','2. 비학술 세미나 기획 및 운영 지표','3. 포인트 지급·사용·잔여 지표'];
export const sources=[
 ['회원분석','https://docs.google.com/spreadsheets/d/18Oaw2ldpiZu_uvaNQG2YNkwou7WWpi6itI-Scjpn070/edit'],
 ['주간 활동성·페이지별 지표','https://docs.google.com/spreadsheets/d/1h-2L8oN7NMJ0BNmc3tJlugis8BetsndeP8-SpG3GgqU/edit'],
 ['비학술 세미나 · raw','https://docs.google.com/spreadsheets/d/1UQqI5Yqjt7pSReSFb0IltpBInHijTFY8eHq0Df-B3Ow/edit'],
 ['포인트 대시보드','https://ojungin.github.io/doctorville_dash/#points']];
export function dayShift(day,n){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function isoWeek(day){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+3-(d.getUTCDay()+6)%7);const year=d.getUTCFullYear(),first=new Date(Date.UTC(year,0,4,12));return year+'-W'+String(1+Math.round((d-first)/604800000)).padStart(2,'0')}
export function numberValue(v){if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(String(v).replace(/[,\s명점%]/g,''));return Number.isFinite(n)?n:null}
function metric(label,value,unit='',previous=null){return {label,value:numberValue(value),unit,previous:numberValue(previous)}}
export function displayMetric(row){const n=numberValue(row.value);return n===null?'자료 미확인':n.toLocaleString('ko-KR',{maximumFractionDigits:2})+(row.unit||'')}
export function comparison(row){const n=numberValue(row.value),p=numberValue(row.previous);if(n===null||p===null)return '';const d=n-p;return '전주 대비 '+(d>0?'+':'')+d.toLocaleString('ko-KR',{maximumFractionDigits:2})+(row.unit||'')+(p===0?' (증감률 산출 불가)':' ('+(d>0?'+':'')+(d/p*100).toFixed(1)+'%)')}
export function emptyMetrics(week){return {version:1,week,fetched_at:null,sections:metricTitles.map(title=>({title,period:week+' ~ '+dayShift(week,6),rows:[],note:'원본 지표를 아직 불러오지 않았습니다.'}))}}
export function metricRows(summary,index){const s=summary?.sections?.[index];return s?.rows?.length?s.rows.map(r=>[r.label,displayMetric(r),comparison(r)]):[['지표','자료 미확인','']]}
export function metricsBody(s){const summary=s.metrics||emptyMetrics(s.week);return metricTitles.map((title,i)=>{const part=summary.sections?.[i]||{},sourceIndexes=i===0?[0,1]:i===1?[2]:[3];return '<section class="report-section"><h2>'+title+'</h2><p class="report-muted">집계 기간: '+e(part.period||s.week+' ~ '+dayShift(s.week,6))+'</p><table><thead><tr><th>지표</th><th>값</th><th>비교</th></tr></thead><tbody>'+metricRows(summary,i).map(r=>'<tr>'+r.map(c=>'<td>'+(c==='자료 미확인'?'<span class="report-missing">'+e(c)+'</span>':e(c))+'</td>').join('')+'</tr>').join('')+'</tbody></table><p class="report-footnote">'+e(part.note||'')+'</p><p class="report-muted">출처: '+sourceIndexes.map(n=>'<a target="_blank" rel="noopener" href="'+sources[n][1]+'">'+e(sources[n][0])+'</a>').join(' · ')+'</p></section>'}).join('')+'<p class="report-muted">지표 조회: '+e(summary.fetched_at||'미조회')+'</p>'}
export function activityMetrics(data,week){const section={title:metricTitles[0],period:week+' ~ '+dayShift(week,6),rows:[],note:''};const prev=dayShift(week,-7),table=data?.weekly,cols=table?.cols||[],rows=table?.rows||[],date=cols.indexOf('주 시작일(월)'),device=cols.indexOf('기기');const find=w=>rows.filter(r=>String(r[date]).slice(0,10)===w&&/^(전체|all|total)$/i.test(String(r[device]).trim())).at(-1);const now=find(week),before=find(prev);if(!now)section.note='해당 주 전체 기기 활동성 자료 미확인. PC/MO 사용자 수를 합산하지 않습니다.';else for(const [label,unit] of [['DAU','명'],['WAU','명'],['MAU','명'],['조회수','회'],['평균세션시간(분)','분']]){const j=cols.indexOf(label);if(j>=0)section.rows.push(metric(label,now[j],unit,before?.[j]))}
 const pages=data?.pageWeekly,pcols=pages?.cols||[],pdate=pcols.indexOf('주 시작일(월)'),pname=pcols.indexOf('페이지그룹'),pv=pcols.indexOf('조회수');if(pdate>=0&&pname>=0&&pv>=0){const latest=new Map();for(const r of pages.rows||[])if(String(r[pdate]).slice(0,10)===week)latest.set(String(r[pname]),r);const top=[...latest.values()].sort((a,b)=>(numberValue(b[pv])||0)-(numberValue(a[pv])||0)).slice(0,5);section.rows.push(...top.map(r=>metric('페이지 조회수 · '+r[pname],r[pv],'회')));if(!top.length)section.note+=' 페이지별 해당 주 자료 미확인.'}
 return section}
export function seminarMetrics(rows,week){const chosen=rows.filter(r=>{const m=String(r[0]).match(/(\d{4})[.\-/]\s*(\d{1,2})[.\-/]\s*(\d{1,2})/);const date=m?m[1]+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0'):'';return date>=week&&date<=dayShift(week,6)});const done=chosen.filter(r=>r[7]===true||String(r[7]).toLowerCase()==='true');const sum=i=>{const ns=done.map(r=>numberValue(r[i])).filter(n=>n!==null);return ns.length?ns.reduce((a,b)=>a+b,0):null},avg=i=>{const ns=done.map(r=>numberValue(r[i])).filter(n=>n!==null);return ns.length?ns.reduce((a,b)=>a+b,0)/ns.length:null};return {title:metricTitles[1],period:week+' ~ '+dayShift(week,6),rows:[metric('편성 세미나',chosen.length,'건'),metric('완료 세미나',done.length,'건'),metric('신청 건수',sum(8),'건'),metric('시청 건수',sum(9),'건'),metric('평균 만족도',avg(10),'점'),metric('평균 유용도',avg(11),'점')],note:'신청·시청은 완료 세미나별 참여 건수 합계이며 고유 회원 수가 아닙니다. 만족도·유용도는 입력된 값의 단순 평균입니다.'}}
export function pointMetrics(data,week){const month=week.slice(0,7),i=data?.months?.indexOf(month)??-1;if(i<0)return {...emptyMetrics(week).sections[2],note:'선택한 월의 포인트 원본 자료가 없습니다. 주간 집계는 원본에 제공되지 않습니다.'};const end=String(data.range?.to||''),monthEnd=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).toISOString().slice(0,10);return {title:metricTitles[2],period:month+'-01 ~ '+(end&&end<monthEnd?end:monthEnd)+' (월 집계)',rows:[metric('지급 포인트',data.earn?.amt?.[i],'P'),metric('사용 포인트',data.use?.amt?.[i],'P'),metric('잔여 포인트 · 지급',data.balance?.[i],'P'),metric('잔여 포인트 · 충전',data.balanceChg?.[i],'P'),metric('잔여 포인트 · 합계',data.balanceTotal?.[i],'P'),metric('소멸 포인트',data.expire?.amt?.[i],'P')],note:'원본은 월별 집계입니다. 해당 주 값으로 간주하지 않으며, 선택한 월 전체 또는 원본 종료일까지의 누계를 표시합니다. 잔여액은 원본 집계 기준이며 '+(data.rules?.balance||'원본의 기초 잔액·제외 규칙을 따릅니다.')}}
async function readJSON(url,options){const response=await fetch(url,{...options,signal:AbortSignal.timeout(45000)});if(!response.ok)throw Error('지표 원본 조회 실패 ('+response.status+')');return response.json()}
export async function loadMetrics(week,password){const summary=emptyMetrics(week);try{summary.sections[1]=await loadSeminarMetrics(week)}catch(err){summary.sections[1].note=err.message}summary.fetched_at=new Date().toISOString();if(!password){summary.sections[0].note='회원·활동성 지표 조회에는 대시보드 비밀번호가 필요합니다.';summary.sections[2].note='포인트 지표 조회에는 대시보드 비밀번호가 필요합니다.';return summary}const base='https://ojungin.github.io/doctorville_dash/',config=await readJSON(base+'data/config.json'),post=body=>readJSON(config.appsScriptUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...body,password})});
 const extended=await post({action:'weeklyReport',weekStart:week}).catch(()=>null);if(extended?.error==='unauthorized'||extended?.error==='locked')throw Error('지표 비밀번호를 확인해주세요.');if(extended?.ok&&extended.week===week&&extended.seminar&&extended.activity){summary.sections[0]=activityMetrics(extended.activity,week);summary.sections[0].rows.unshift(metric('신규 회원',extended.member?.newWeek,'명',extended.member?.newPrevWeek));summary.sections[0].note+=' 신규 회원은 가입일 기준이며 탈퇴를 포함한 순증감은 미확인입니다.'}else{const activity=await post({action:'activity'});if(!activity.ok)throw Error(activity.error||'지표 인증에 실패했습니다.');summary.sections[0]=activityMetrics(activity.activity,week);const member=await post({action:'get',week:isoWeek(week)}).catch(()=>null);if(member?.snap?.weekStart===week){summary.sections[0].rows.unshift(metric('신규 회원',member.snap.kpi?.newWeek,'명',member.snap.kpi?.newPrevWeek));summary.sections[0].note+=' 신규 회원은 회원분석 가입일 기준입니다. 탈퇴를 포함한 순증감은 원본에 별도 값이 없어 미확인입니다.'}else summary.sections[0].note+=' 해당 주 신규 회원 자료 미확인.'}
 try{const [meta,box]=await Promise.all([readJSON(base+'data/meta.json'),readJSON(base+'data/points.enc.json')]);const unb64=x=>Uint8Array.from(atob(x),c=>c.charCodeAt(0)),seed=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:unb64(meta.salt),iterations:meta.iter},seed,{name:'AES-GCM',length:256},false,['decrypt']);const decode=async b=>JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(b.iv)},key,unb64(b.ct))));await decode(meta.check);summary.sections[2]=pointMetrics(await decode(box),week)}catch{summary.sections[2].note='포인트 암호화 원본을 불러오지 못했습니다. 원본을 확인 후 집계값을 입력해주세요.'}
 summary.fetched_at=new Date().toISOString();return summary}

export const seminarSourceURL='https://docs.google.com/spreadsheets/d/1UQqI5Yqjt7pSReSFb0IltpBInHijTFY8eHq0Df-B3Ow/gviz/tq?gid=1830918551&range=D1%3AO1000&headers=1';
export function parseGVizResponse(text){const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start<0||end<start)throw Error('세미나 원본 응답을 확인할 수 없습니다.');return JSON.parse(text.slice(start,end+1))}
export function seminarRowsFromTable(response){if(response.status!=='ok'||!response.table)throw Error('세미나 시트 공유 권한과 원본 상태를 확인해주세요.');const table=response.table,expected={0:'일자',7:'완료',8:'신청자 수',9:'시청자 수',10:'만족도',11:'유용도'};
 for(const [i,label] of Object.entries(expected))if(String(table.cols?.[i]?.label||'').replace(/\s/g,'')!==label.replace(/\s/g,''))throw Error('세미나 raw 시트의 열 구성이 변경되었습니다: '+label);
 return (table.rows||[]).map(row=>Array.from({length:12},(_,i)=>{const cell=row.c?.[i];let value=cell?.v??cell?.f??'';if(i===0){if(value instanceof Date)return value.getFullYear()+'-'+String(value.getMonth()+1).padStart(2,'0')+'-'+String(value.getDate()).padStart(2,'0');const match=String(value).match(/^Date\((\d{4}),(\d{1,2}),(\d{1,2})(?:,.*)?\)$/);if(match)value=match[1]+'-'+String(Number(match[2])+1).padStart(2,'0')+'-'+match[3].padStart(2,'0')}return value}))
}
let seminarQueryId=0;
export function querySeminarSheet(){return new Promise((resolve,reject)=>{const callback='weeklySeminarResponse_'+(++seminarQueryId),script=document.createElement('script');let timer;
 const clean=()=>{clearTimeout(timer);script.remove();delete window[callback]};
 window[callback]=response=>{clean();resolve(response)};script.onerror=()=>{clean();reject(Error('세미나 원본을 불러오지 못했습니다. 네트워크와 공유 권한을 확인해주세요.'))};
 timer=setTimeout(()=>{clean();reject(Error('세미나 원본 조회 시간이 초과되었습니다. 다시 조회해주세요.'))},30000);
 script.src=seminarSourceURL+'&tqx='+encodeURIComponent('out:json;responseHandler:'+callback);document.head.append(script);
})}
export async function loadSeminarMetrics(week,query=querySeminarSheet){const response=await query(),rows=seminarRowsFromTable(response),part=seminarMetrics(rows,week);part.fetched_at=new Date().toISOString();part.note+=' Google Sheets raw 직접 조회 · 조회 '+part.fetched_at;return part}
